### ISSUE TITLE
Provider.js path in lib for npm package is wrong

### ISSUE THREAD

**Issue by averageflamethrowerguy** [nteract/mathjax#10]
While /src has the correct route, provider.js in /lib still has the broken Cloudflare route after installing from npm (https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.8/MathJax.js?config=TeX-MML-AM_CHTML).
I am using v4.0.11, which I believe is the latest release.

Everything works after editing the route to https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js?config=TeX-MML-AM_CHTML

**Comment by captainsafia** [comment]
Thanks for reporting! Can you try the newly released 4.0.12?

**Comment by averageflamethrowerguy** [comment]
Wow! Thanks for the fast reply!
4.0.12 seems to have the correct path update. Unfortunately, I'm now getting 'Module not found: ./context in node-modules/mathjax/lib' when I do npm start.
It does look like context.js and context.d.tsx both existed in the last version. And context.tsx exists in /src of this version, so it probably just needs to be built into /lib.

**Comment by captainsafia** [comment]
Blegh -- try 4.0.13?

This is my bad. Our publishing infra for the packages that we moved out of the monorepo is....not ideal at the moment.

**Comment by averageflamethrowerguy** [comment]
All looks good from my end. 
Thanks for all your help / quick responses!
