### ISSUE TITLE
lib folder is missing in v4.0.8

### ISSUE THREAD

**Issue by chenxinyanc** [nteract/mathjax#4]
See https://unpkg.com/browse/@nteract/mathjax@4.0.8/
The entry-point is specified here: https://github.com/nteract/mathjax/blob/e2ca414c97297e51951bcd53e2da0992ad3e1b28/package.json#L5

But the published package does not have this file.

**Comment by bfkenny** [comment]
Seconding this!

**Comment by 3xau1o** [comment]
third!!! fixed files:
[build files @nteract.zip](https://github.com/nteract/mathjax/files/4741228/build.files.%40nteract.zip)

**Comment by ramantehlan** [comment]
Thank you @chenxinyanc for pointing it out. We will have to rebuild the packages to fix it, as mentioned in this [comment](https://github.com/nteract/markdown/issues/6#issuecomment-640270783).

**Comment by captainsafia** [comment]
Resolved in 4.0.9.

Edit: Apologies for the delay folks! It looks like I wasn't set to watch mode in this repository so I didn't receive a notification when this issue was opened.
