### ISSUE TITLE
Incorrect URL of MathJax 2.7.8 library

### ISSUE THREAD

**Issue by bryanchen-d** [nteract/mathjax#5]
The cloudfare url returned 404. 

From MathJax's site (https://www.mathjax.org/MathJax-v2-7-8-available/), the correct one should be 'https://cdn.jsdelivr.net/npm/mathjax@2.7.8/MathJax.js?config=TeX-MML-AM_CHTML'

**Comment by captainsafia** [comment]
Can you submit a PR with a fix?

**Comment by manoelcfeliciano** [comment]
@captainsafia I think the fix has not been published to npm properly although the fix has been merged into master.

**Comment by captainsafia** [comment]
Fix has been pushed in v4.0.10.
