### ISSUE TITLE
MathJax cdn url returns 404 Error

### ISSUE THREAD

**Issue by stormpython** [nteract/mathjax#8]
The `cdnjs` address [here](https://github.com/nteract/mathjax/blob/a25c6d8ff451ef397a7b4c6540066746653b1464/src/provider.tsx#L30) is not valid. MathJax version `2.7.8` does not exist. Please see [here](https://cdnjs.com/libraries/mathjax/2.7.9).

This should probably be updated to the latest, which is [3.1.0](https://cdnjs.com/libraries/mathjax/3.1.0).

**Comment by stormpython** [comment]
Perhaps `2.7.9` would be a better choice for now.

**Comment by captainsafia** [comment]
@stormpython Hm. The address doesn't 404 for me, which was part of my motivation for merging that change.

I'm fine with upgrading. Are you interested in submitting a PR for that?

**Comment by stormpython** [comment]
@captainsafia yes, I'll submit a PR for this issue.

It's weird because I was getting a 404 earlier, but I was also on my company's VPN. Off of the VPN, the cdn works, but that version does not exist on `cdnjs`.

**Comment by captainsafia** [comment]
> It's weird because I was getting a 404 earlier, but I was also on my company's VPN. Off of the VPN, the cdn works, but that version does not exist on cdnjs.

Maybe it's cached somewhere? In that case, upgrading should cover us.
